/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as ApiPublicV1PasteRouteImport } from './routes/api/public/v1/paste'
import { Route as ApiPublicV1PasteIdRouteImport } from './routes/api/public/v1/paste.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PasteRoute = ApiPublicV1PasteRouteImport.update({
  id: '/api/public/v1/paste',
  path: '/api/public/v1/paste',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PasteIdRoute = ApiPublicV1PasteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1PasteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/p/$id': typeof PIdRoute
  '/api/public/v1/paste': typeof ApiPublicV1PasteRouteWithChildren
  '/api/public/v1/paste/$id': typeof ApiPublicV1PasteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/p/$id': typeof PIdRoute
  '/api/public/v1/paste': typeof ApiPublicV1PasteRouteWithChildren
  '/api/public/v1/paste/$id': typeof ApiPublicV1PasteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/p/$id': typeof PIdRoute
  '/api/public/v1/paste': typeof ApiPublicV1PasteRouteWithChildren
  '/api/public/v1/paste/$id': typeof ApiPublicV1PasteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/sitemap.xml'
    | '/p/$id'
    | '/api/public/v1/paste'
    | '/api/public/v1/paste/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/sitemap.xml'
    | '/p/$id'
    | '/api/public/v1/paste'
    | '/api/public/v1/paste/$id'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/sitemap.xml'
    | '/p/$id'
    | '/api/public/v1/paste'
    | '/api/public/v1/paste/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PIdRoute: typeof PIdRoute
  ApiPublicV1PasteRoute: typeof ApiPublicV1PasteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/paste': {
      id: '/api/public/v1/paste'
      path: '/api/public/v1/paste'
      fullPath: '/api/public/v1/paste'
      preLoaderRoute: typeof ApiPublicV1PasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/paste/$id': {
      id: '/api/public/v1/paste/$id'
      path: '/$id'
      fullPath: '/api/public/v1/paste/$id'
      preLoaderRoute: typeof ApiPublicV1PasteIdRouteImport
      parentRoute: typeof ApiPublicV1PasteRoute
    }
  }
}

interface ApiPublicV1PasteRouteChildren {
  ApiPublicV1PasteIdRoute: typeof ApiPublicV1PasteIdRoute
}

const ApiPublicV1PasteRouteChildren: ApiPublicV1PasteRouteChildren = {
  ApiPublicV1PasteIdRoute: ApiPublicV1PasteIdRoute,
}

const ApiPublicV1PasteRouteWithChildren =
  ApiPublicV1PasteRoute._addFileChildren(ApiPublicV1PasteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PIdRoute: PIdRoute,
  ApiPublicV1PasteRoute: ApiPublicV1PasteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
