/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as AuthenticatedMyRouteImport } from './routes/_authenticated/my'
import { Route as AuthenticatedEditIdRouteImport } from './routes/_authenticated/edit.$id'
import { Route as ApiPublicV1PasteRouteImport } from './routes/api/public/v1/paste'
import { Route as ApiPublicV1PasteIdRouteImport } from './routes/api/public/v1/paste.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyRoute = AuthenticatedMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditIdRoute = AuthenticatedEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicV1PasteRoute = ApiPublicV1PasteRouteImport.update({
  id: '/api/public/v1/paste',
  path: '/api/public/v1/paste',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PasteIdRoute = ApiPublicV1PasteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1PasteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/my': typeof AuthenticatedMyRoute
  '/p/$id': typeof PIdRoute
  '/edit/$id': typeof AuthenticatedEditIdRoute
  '/api/public/v1/paste': typeof ApiPublicV1PasteRouteWithChildren
  '/api/public/v1/paste/$id': typeof ApiPublicV1PasteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/my': typeof AuthenticatedMyRoute
  '/p/$id': typeof PIdRoute
  '/edit/$id': typeof AuthenticatedEditIdRoute
  '/api/public/v1/paste': typeof ApiPublicV1PasteRouteWithChildren
  '/api/public/v1/paste/$id': typeof ApiPublicV1PasteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/my': typeof AuthenticatedMyRoute
  '/p/$id': typeof PIdRoute
  '/_authenticated/edit/$id': typeof AuthenticatedEditIdRoute
  '/api/public/v1/paste': typeof ApiPublicV1PasteRouteWithChildren
  '/api/public/v1/paste/$id': typeof ApiPublicV1PasteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/sitemap.xml'
    | '/my'
    | '/p/$id'
    | '/edit/$id'
    | '/api/public/v1/paste'
    | '/api/public/v1/paste/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/sitemap.xml'
    | '/my'
    | '/p/$id'
    | '/edit/$id'
    | '/api/public/v1/paste'
    | '/api/public/v1/paste/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/sitemap.xml'
    | '/_authenticated/my'
    | '/p/$id'
    | '/_authenticated/edit/$id'
    | '/api/public/v1/paste'
    | '/api/public/v1/paste/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PIdRoute: typeof PIdRoute
  ApiPublicV1PasteRoute: typeof ApiPublicV1PasteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my': {
      id: '/_authenticated/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthenticatedMyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edit/$id': {
      id: '/_authenticated/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof AuthenticatedEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/v1/paste': {
      id: '/api/public/v1/paste'
      path: '/api/public/v1/paste'
      fullPath: '/api/public/v1/paste'
      preLoaderRoute: typeof ApiPublicV1PasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/paste/$id': {
      id: '/api/public/v1/paste/$id'
      path: '/$id'
      fullPath: '/api/public/v1/paste/$id'
      preLoaderRoute: typeof ApiPublicV1PasteIdRouteImport
      parentRoute: typeof ApiPublicV1PasteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMyRoute: typeof AuthenticatedMyRoute
  AuthenticatedEditIdRoute: typeof AuthenticatedEditIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMyRoute: AuthenticatedMyRoute,
  AuthenticatedEditIdRoute: AuthenticatedEditIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicV1PasteRouteChildren {
  ApiPublicV1PasteIdRoute: typeof ApiPublicV1PasteIdRoute
}

const ApiPublicV1PasteRouteChildren: ApiPublicV1PasteRouteChildren = {
  ApiPublicV1PasteIdRoute: ApiPublicV1PasteIdRoute,
}

const ApiPublicV1PasteRouteWithChildren =
  ApiPublicV1PasteRoute._addFileChildren(ApiPublicV1PasteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PIdRoute: PIdRoute,
  ApiPublicV1PasteRoute: ApiPublicV1PasteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
