/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as ApiV1PasteRouteImport } from './routes/api/v1/paste'
import { Route as ApiV1PasteIdRouteImport } from './routes/api/v1/paste.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PasteRoute = ApiV1PasteRouteImport.update({
  id: '/api/v1/paste',
  path: '/api/v1/paste',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PasteIdRoute = ApiV1PasteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1PasteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/p/$id': typeof PIdRoute
  '/api/v1/paste': typeof ApiV1PasteRouteWithChildren
  '/api/v1/paste/$id': typeof ApiV1PasteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/p/$id': typeof PIdRoute
  '/api/v1/paste': typeof ApiV1PasteRouteWithChildren
  '/api/v1/paste/$id': typeof ApiV1PasteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/p/$id': typeof PIdRoute
  '/api/v1/paste': typeof ApiV1PasteRouteWithChildren
  '/api/v1/paste/$id': typeof ApiV1PasteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search' | '/p/$id' | '/api/v1/paste' | '/api/v1/paste/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search' | '/p/$id' | '/api/v1/paste' | '/api/v1/paste/$id'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/p/$id'
    | '/api/v1/paste'
    | '/api/v1/paste/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  PIdRoute: typeof PIdRoute
  ApiV1PasteRoute: typeof ApiV1PasteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/paste': {
      id: '/api/v1/paste'
      path: '/api/v1/paste'
      fullPath: '/api/v1/paste'
      preLoaderRoute: typeof ApiV1PasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/paste/$id': {
      id: '/api/v1/paste/$id'
      path: '/$id'
      fullPath: '/api/v1/paste/$id'
      preLoaderRoute: typeof ApiV1PasteIdRouteImport
      parentRoute: typeof ApiV1PasteRoute
    }
  }
}

interface ApiV1PasteRouteChildren {
  ApiV1PasteIdRoute: typeof ApiV1PasteIdRoute
}

const ApiV1PasteRouteChildren: ApiV1PasteRouteChildren = {
  ApiV1PasteIdRoute: ApiV1PasteIdRoute,
}

const ApiV1PasteRouteWithChildren = ApiV1PasteRoute._addFileChildren(
  ApiV1PasteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  PIdRoute: PIdRoute,
  ApiV1PasteRoute: ApiV1PasteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
